### ISSUE TITLE
Make the package stable.

### ISSUE THREAD

**Issue by nilportugues** [thecodingmachine/symfony-middleware#2]
Hello @moufmouf! Thanks for releasing this :+1: 

Would you mind tagging the current dev-master branch and release it as stable, (maybe release 0.1.0) ? 

Thanks!

**Comment by moufmouf** [comment]
You are completely right, I should have done this a long time ago!
:+1:

**Comment by nilportugues** [comment]
Thanks! :100: :tada:  

/cc @theUniC :+1:
